# Generated by Django 5.0.6 on 2024-05-29 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('objective', models.TextField()),
                ('home_ingredients', models.TextField()),
                ('box_ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('explanation', models.TextField()),
                ('custom_command', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='products.product')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='titles.title')),
            ],
            options={
                'unique_together': {('title', 'product', 'serial_number')},
            },
        ),
    ]
